FROM node:20-alpine

COPY sync_db.sh /sync_db.sh

RUN chmod +x /sync_db.sh

RUN apk add rclone

RUN npm install -g 9router

EXPOSE 20128

ENTRYPOINT ["sh", "-c", "sh /sync_db.sh && 9router --skip-update --tray"]
